version: 0.2

env:
  variables:
    IMAGE_TAG: latest
    ECR_REPO: 415665903242.dkr.ecr.us-east-1.amazonaws.com/hub/nodejs

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REPO"
      - REPOSITORY_URI=$ECR_REPO
      - IMAGE=$REPOSITORY_URI:$IMAGE_TAG
      - echo "Building image: $IMAGE"

  build:
    commands:
      - echo Build started on `date`
      - docker build -t $IMAGE .

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $IMAGE
      - echo Image pushed: $IMAGE

artifacts:
  files: []
